---
- name: Install nerdctl-full
  ansible.builtin.get_url:
    url: "{{ nerdctl_binary_url }}"
    checksum: "{{ nerdctl_checksum }}"
    dest: "{{ nerdctl_zip_dest }}"
  register: nerdctl

- name: Unzip
  ansible.builtin.unarchive:
    src: "{{ nerdctl.dest }}"
    dest: "{{ nerdctl_dest }}"
    remote_src: true

- name: Remove zip file
  ansible.builtin.file:
    path: "{{ nerdctl_zip_dest }}"
    state: absent
