---
- name: Install iptables
  ansible.builtin.dnf:
    name: iptables
    state: present

- name: Install nerdctl-full
  ansible.builtin.get_url:
    url: "{{ nerdctl_binary_url }}"
    checksum: "{{ nerdctl_checksum }}"
    dest: "{{ nerdctl_zip_dest }}"
  register: nerdctl

- name: Unzip
  ansible.builtin.unarchive:
    src: "{{ nerdctl.dest }}"
    dest: "{{ nerdctl_dest }}"
    remote_src: true

- name: Remove zip file
  ansible.builtin.file:
    path: "{{ nerdctl_zip_dest }}"
    state: absent

- name: Create nerdctl config directory
  ansible.builtin.file:
    path: /etc/nerdctl
    state: directory
    mode: '0755'

- name: Configure CNI_PATH
  ansible.builtin.copy:
    dest: /etc/nerdctl/nerdctl.toml
    content: |
      cni_path = "{{ nerdctl_dest }}/libexec/cni"
    mode: '0644'
