---
plugin: amazon.aws.aws_ec2
regions:
  - us-west-1
filters:
  tag:Name:
    - k3s-server-prod
    - k3s-server-dev
  instance-state-name: running
hostnames:
  - tag:Name
compose:
  ansible_host: instance_id
groups:
  server: "'k3s-server' in tags.Name"
